### ISSUE TITLE
'ascii' codec can't encode character u'\xea' in position 21: ordinal not in range(128)

### ISSUE THREAD

**Issue by felinto-dev** [HXL-CPLP/assistente-hashtags-hxl#1]
Olá,

Parabéns pelo incrível projeto! Preciso fazer um sistema especialista para faculdade de IA e estava tentando usar o seu como base mas quando fui tentar executar aqui recebi esse seguinte erro:

```
emers@DESKTOP-QNKQ23K MINGW64 ~/Documents/assistente-hashtags-hxl (master)
$ python gen-chooser.py >> docs/index.html
Traceback (most recent call last):
  File "gen-chooser.py", line 123, in <module>
    display_question("top")
  File "gen-chooser.py", line 34, in display_question
    print("      <h2>{}</h2>".format(esc(question["question"])))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xea' in position 21: ordinal not in range(128)
```

Devido à outro problema também que tive ao tentar executar o arquivo, tive que adicionar isso no começo dele:
`# encoding=utf8`

Estou usando Python 2.7 porque foi a que eu deduzi que você estava usando. Caso esteja usando outra me diga.

Você pode me dá mais detalhes sobre qual versão python você usou para executar esses comandos ou qual sistema operacional está utilizando ?

**Comment by fititnt** [comment]
Olá Emerson, seja bem vindo!

```bash
# fititnt at bravo in /alligo/code/hxl-cplp/assistente-hashtags-hxl on git:master o [15:20:22]
$ python --version
Python 3.7.5
```

Estamos usando o 3.7. Caso queira pode ou testar nesta versão, ou se prefere usar o Python 2.7 pode enviar um pull request para este repositório com a correção que propôs já por texto. Faço um teste

### Sobre a questão de usar como base de sistema especialista

A licença é domínio publico, então pode ficar livre para usar, inclusive poder re-licenciar (o que pode acabar sendo necessário caso você tenha no seu projeto outras licenças que sejam mais restritivas).

Também recomendo você acabar fazendo um hardfork (ou seja, não fazer um fork do github, mas simplesmente copiar o arquivo e fazer alterações necessárias) pois algo que não seja assistente de hashtags para o padrão HXL seria bem diferente. Outro ponto é que isso lhe dá mais liberdade!

**Comment by felinto-dev** [comment]
Você me respondeu, nossa, obrigado!

Eu planejo adaptar sim esse projeto, mas o legal é que eu quero em vez de utilizar uma interface web, utilizar um chatbot, como o Telegram, WhatsApp, etc. Vou tentar fazer usando a base de conhecimento deste projeto primeiramente, e quando tiver pronto, posso postar o código aqui. Dessa forma, usando a mesma base de conhecimento vocês poderiam criar um chatbot no telegram também. É bem fácil.

Vou tentar aqui novamente e caso tenha problemas, retorno esse issue.

**Comment by fititnt** [comment]
FANTASTICO!

Neste caso acho que o que provavelmente você iria acabar fazendo é aproveitar a forma como a base de conhecimento foi encodada em .json, mas em de gerar o HTML, gera perguntas de chatbot.

Realmente, se você conseguir reutilizar mais ou menos a mesma estrutura de json (ou então, mesmo que tenha opções extras, o "fallback" seja o encoding atual) na pratica a sua implementação serve para ser usada em outros projetos. (Porém nada impede da gente fazer algumas alterações na base JSON atual se isso tornar ela mais flexivel).

Uma coisa que você pode fazer é usar o `HXL-CPLP/assistente-hashtags-hxl` (em especial o banco de dados dele) como prova de conceito que de fato seria usada em produção. Quanto a questão de drivers, creio que do telegram seja o mais fácil de implementar (Facebook messager depende de aprovação, twitter também tem demorado, e WhatsApp é especialmente complicado).

@felinto-dev se quiser, pode me adicionar no Facebook https://www.facebook.com/fititnt ou mandar e-mail para rocha@ieee.org que passo outros dados meus para você ficar diretamente em contato. Faço questão de te ajudar em outras coisas!

**Comment by felinto-dev** [comment]
@fititnt, estou fazendo justamente para o Telegram nesse momento. Realmente é bem intuitivo.

A ideia é justamente essa. Estou tentando entender ainda a lógica de como o conhecimento deste sistema especialista está estruturado para tentar adaptar para a minha aplicação, então estou estudando o código Python.

Muito obrigado pela sua disposição em ajudar, sucesso!
